export const colors = {
  background:      '#0A0A0A',
  surface:         '#141414',
  surfaceElevated: '#1E1E1E',
  border:          '#2A2A2A',
  primary:         '#FF3C3C',
  primaryDark:     '#CC1F1F',
  success:         '#00C853',
  warning:         '#FFB300',
  error:           '#FF3C3C',
  textPrimary:     '#FFFFFF',
  textSecondary:   '#8A8A8A',
  textMuted:       '#555555',
  overlay:         'rgba(0,0,0,0.6)',
  white:           '#FFFFFF',
  transparent:     'transparent',
};
